on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Step 1
        run: echo "Hello, GitHub!"
      
      - name: Step 2
        run: echo "Proft has been made."